POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpkbGMiLCJpZCI6IjVmMGMyODgzNDA3YjlmNDE1Y2Q2MGQ4NSIsImlhdCI6MTU5NDY0MjYwMX0.fZ6EIikFX4Q_I3ljtF1fvgg28QzlZrJXOWzDAJJWWA0

{
  "title": "Another one by user with token",
  "author": "VS Code Rest Client",
  "url": "http://newblogpost.com/properUserCreated",
  "likes": 0
}