POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "App separated into its own module",
  "author": "VS Code Rest Client",
  "url": "http://newblogpost.com/separateAppModule",
  "likes": 0
}